[package]
name = "pebr-benchmark"
version = "0.1.0"
authors = ["Jerry Jaehwang Jung <tomtomjhj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
clap = "2.33.0"
# crossbeam-epoch = "0.7.1"
# crossbeam-utils = "0.6.5"
crossbeam-epoch = { git = "https://github.com/tomtomjhj/crossbeam", path = "crossbeam-epoch", branch = "tracker-ebr"}
crossbeam-utils = { git = "https://github.com/tomtomjhj/crossbeam", path = "crossbeam-utils", branch = "tracker-ebr"}
csv = "1.1.1"
jemallocator = "0.3.0"
rand = "0.7"

[profile.release]
debug = true
